"""Shared pytest fixtures."""

from __future__ import annotations

import os
from collections.abc import Iterator
from pathlib import Path
from tempfile import TemporaryDirectory

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine
from sqlalchemy.orm import Session, sessionmaker

from app.core.config import get_settings
from app.db import models  # noqa: F401  - register models on Base.metadata
from app.db.base import Base
from app.db.session import get_db


def _test_database_url() -> str:
    return os.environ.get(
        "TEST_DATABASE_URL",
        "postgresql+psycopg://casa:casa@localhost:5432/casa_test",
    )


@pytest.fixture(scope="session")
def db_engine() -> Iterator[Engine]:
    engine = create_engine(_test_database_url(), future=True)
    # Ensure required extensions are present and schema is up-to-date.
    with engine.begin() as conn:
        conn.execute(text('CREATE EXTENSION IF NOT EXISTS "pgcrypto"'))
        Base.metadata.create_all(conn)
    yield engine
    engine.dispose()


@pytest.fixture()
def db_session(db_engine: Engine) -> Iterator[Session]:
    """Provide a transactional session that rolls back after each test."""

    connection = db_engine.connect()
    trans = connection.begin()
    session_factory = sessionmaker(
        bind=connection, autoflush=False, autocommit=False, future=True
    )
    session = session_factory()
    try:
        yield session
    finally:
        session.close()
        trans.rollback()
        connection.close()


@pytest.fixture(autouse=True)
def isolated_storage(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Iterator[Path]:
    """Point the storage root at a per-test tmpdir."""

    storage_root = tmp_path / "storage"
    storage_root.mkdir(parents=True, exist_ok=True)
    monkeypatch.setenv("STORAGE_ROOT", str(storage_root))
    get_settings.cache_clear()
    yield storage_root
    get_settings.cache_clear()


@pytest.fixture()
def client(db_session: Session) -> Iterator[TestClient]:
    """FastAPI TestClient bound to the per-test transactional session."""

    from app.main import create_app

    app = create_app()

    def override_get_db() -> Iterator[Session]:
        yield db_session

    app.dependency_overrides[get_db] = override_get_db
    with TestClient(app) as c:
        yield c
    app.dependency_overrides.clear()


@pytest.fixture()
def vector_pdf_bytes() -> bytes:
    """A small in-memory vector PDF generated by PyMuPDF."""

    import fitz

    doc = fitz.open()
    for i in range(2):
        page = doc.new_page(width=595, height=842)
        page.insert_text((72, 72), f"Sample vector page {i + 1}")
        page.draw_line((72, 100), (500, 100))
    data = doc.tobytes()
    doc.close()
    return bytes(data)


@pytest.fixture()
def fixture_pdf_dir() -> Path:
    return Path(__file__).parent / "fixtures"


@pytest.fixture()
def tempdir() -> Iterator[Path]:
    with TemporaryDirectory() as td:
        yield Path(td)
